### ISSUE TITLE
New geometries pickled using python 3 only support

### ISSUE THREAD

**Issue by adler-j** [davlars/ad-skull-reconstruction#15]
You get the following error when you try to load the geometries

```
ValueError: unsupported pickle protocol: 3
```

To solve this, we need to regenerate these with protocol version 2. I.e. someone with python3 needs to do:

```
pickle.dump(pickle.load(file), file, 2)
```

on all the geometry files.

**Comment by davlars** [comment]
Done. Files are saved in the usual place (reachable using standard `adutils.load_data_from_nas`). I'm thinking whether we'll have an issue with conflicting python2, python3 in the future (would python 3 not like a pickle version2 file?)?. Might create pickled version for both and check which one to use in the utilities. Leaving this open until that's potentially done.

**Comment by adler-j** [comment]
Python 3 works fine with python 2 style pickled files, so just leave it as is for now.

**Comment by davlars** [comment]
Great.
