### ISSUE TITLE
Reasoning for keeping data and phantom on different locations

### ISSUE THREAD

**Issue by adler-j** [davlars/ad-skull-reconstruction#21]
Basically this makes the `load_data_from_nas` script fail, at least on windows. This is because `Reference` and `Users` are on different drives.

**Comment by adler-j** [comment]
Got this fixed now, only a minor issue remains, that we don't check for the paths properly. I'll make a PR.

**Comment by davlars** [comment]
Nice! Assuming that you're referring to #22
