### ISSUE TITLE
Add example of how to load data on linux

### ISSUE THREAD

**Issue by adler-j** [davlars/ad-skull-reconstruction#28]
The current example in the readme only works properly on windows, a short example on linux usage would probably be popular.

**Comment by davlars** [comment]
Changing the path to the corresponding one in linux works fine for me. Would you say that explicitly showing such in the readme is needed? If so a very minor addition can be seen in e86bce32cd19bc5b2e3f2f359ac6a8d48f4b5589. Or are there other issues that needs to be explicitly explained?

**Comment by adler-j** [comment]
Well, I was helping some people out and this seemed very unclear to basically everyone (noone I asked was actually loading data property, everyone did some hacky workaround) so it seems this is indeed very hard to understand.

Perhaps we need to add explicit examples (e.g. what the path can be) and/or instructions on how to get it?

**Comment by davlars** [comment]
Ok... I'll double check how I mounted the nas and add some example on that. Once it's mounted, the utility works fine though

**Comment by davlars** [comment]
The main problem has obviously been to get a proper imagingnas mount point (on linux machines). I've now made some instructions for that ([here](https://davlars.github.io/how_to_mount_imagingnas.github.io/)) and added the link to the readme. Closing this for now.

**Comment by adler-j** [comment]
Great guide!
