### ISSUE TITLE
plot_data for 2d

### ISSUE THREAD

**Issue by adler-j** [davlars/ad-skull-reconstruction#29]
Currently running plot_data on a 2d data set gives an error. Perhaps we should also support 2d?

**Comment by davlars** [comment]
In a way visualizing the 2D data set is trivial (using the old ```*.show()```); the ```plot_data``` utility is basically there to make us visualize the same 2D slices of a 3D reconstruction.

With that said, it can be good to use the same code style for the 2D and 3D cases (i.e. calling ```plot_data```when you want to visualize stuff) so I agree that it should be supported. I'll try to add this shortly.

**Comment by davlars** [comment]
Now supported after baf719d6b52584d6a14cc41f7add2806cdb0c7fb
