### ISSUE TITLE
Problem with installing requirements.txt

### ISSUE THREAD

**Issue by hilding79** [davlars/ad-skull-reconstruction#31]
I have problem with installing requirements. What is going wrong? Anyone else has the same issue?

I write the following command:

```
:~/ad-skull-reconstruction$ pip install -r requirements.txt
```

I get the error message:

```
Collecting odl>=0.6.1 (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement odl>=0.6.1 (from -r requirements.txt (line 1)) (from versions: 0.2.2, 0.2.3, 0.3.0, 0.3.1, 0.4.0, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.3.post0, 0.5.3.post1, 0.5.3.post2, 0.6.0)
No matching distribution found for odl>=0.6.1 (from -r requirements.txt (line 1))
```

**Comment by aringh** [comment]
It looks like there is [no release](https://github.com/odlgroup/odl/releases) of `odl` with version number 0.6.1...

Quickest fix for you right now is just to open the txt-file and manually, using `pip`, installing the packages listed in it.

**Comment by adler-j** [comment]
Well, you need odl 0.6.1 in order to run the examples so the easiest fix is to install it manually, i.e. via:

```
pip install git+git://github.com/odlgroup/odl
```

or an actual source

```
git clone https://github.com/odlgroup/odl
cd odl
pip install -e .
```

Perhaps we could update the requirements file to somehow know that github exists, but I'm not sure how to do that.
