### ISSUE TITLE
Save_data does not seem to exist

### ISSUE THREAD

**Issue by hilding79** [davlars/ad-skull-reconstruction#32]
`save_data` does not seem to exist in adutils. Instead I find `save_image`, which seems to do the job. Need to update documentation accordingly (see below).

> Save data
> 
> To save data in a format that the clinical can review (typically nifti), use the adutils.save_data utility, with x being your reconstruction
> 
> fileName = /my/path/myFile
> adutils.save_data(x, fileName, as_nii=True, as_npy=True)

**Comment by davlars** [comment]
You're right. It was renamed in 0864b2fd442412808cc3688eac7edca162f8db54, but we forget the readme. Has been fixed by 259c8f420f2f9fcca87bd11d7c7a95eb2555074c. Thanks!
