### ISSUE TITLE
`import adutils` requires X server

### ISSUE THREAD

**Issue by sbanert** [davlars/ad-skull-reconstruction#40]
When connect to a remote computer via SSH, start an IPython session and type `import adutils` (which is properly installed), I get the error message
```
qt.qpa.screen: QXcbConnection: Could not connect to display 
Could not connect to any X display.
```

**Comment by adler-j** [comment]
I guess it's one of these lines:

https://github.com/davlars/ad-skull-reconstruction/blob/7a85ba18ea80fee1be6b8dc66b2058430e119fef/adutils/utilities.py#L15-L16

Try commenting them out.

**Comment by sbanert** [comment]
It’s only `matplotlib.pyplot`.

**Comment by adler-j** [comment]
Can you make a PR to change those to be lazily imported? Should solve this issue.
